changelog:
  categories:
    - title: What's Changed
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
        authors:
          - dependabot
          - dependabot[bot]
          - renovate
          - renovate[bot]
    - title: Dependencies
      labels:
        - "*"
