# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
builds:
  - env:
      - CGO_ENABLED=0
    id: "fs_rs"
    builder: rust
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-unknown-linux-musl
      - x86_64-pc-windows-gnu
    command: build
    flags:
      - "--release"
archives:
  - format_overrides:
      - goos: windows
        formats: [ 'zip' ]

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}"